
###
DELETE http://bitcoin.linkpc.net:3000/api/persons/1

###
GET http://bitcoin.linkpc.net:3000/api/persons

###
HEAD  http://bitcoin.linkpc.net:3000/api/persons

###
OPTIONS   http://bitcoin.linkpc.net:3000/api/persons


###
POST http://bitcoin.linkpc.net:3000/api/persons HTTP/1.1
content-type: application/json

{
    "name": "police station",
    "number": "010-1001001111"
}

###
GET http://bitcoin.linkpc.net:3000/api/persons/1


###
GET http://bitcoin.linkpc.net:3000/api/persons12/1